// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udfpkzipkedhziifcozh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZnBremlwa2VkaHppaWZjb3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODU0NzAsImV4cCI6MjA3Mjk2MTQ3MH0.1uCZZe7ItVazwAInjRzJJd7zgNK7qpelSOk3XyMPIf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});